#!/usr/bin/env python3
#
# pystylus - the executable
#
"""
Easy front-end for the runnable portion of pystylus package.
"""

import sys

from pystylus.__main__ import main

sys.exit(main(sys.argv[1:]))
